Dev
Lesnoi3283/yandex_gophermart pull request #15
Opened 2024-08-18 15:14 UTC by Lesnoi3283

2024-08-22 22:36 UTC, avhitrov requested changes
Замечания в комментариях к коду.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/accrualdaemon/accrual_daemon.go
> +					continue
Не вижу разницы между этими условиями.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/accrualdaemon/accrual_daemon.go
> +			break loop
```suggestion
			return
```
Мы все равно выходим из цикла в конец функции. Нет смысла городить конструкцию с break.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/accrualdaemon/accrual_daemon.go
> +
Если не хотим заспамить собственную БД, нужно делать time.Sleep. Длительностью побольше (скажем, 30 сек), если ничего не прочиталось и длительностью поменьше (скажем, 100ms), если что-то прочиталось.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/accrualdaemon/accrual_daemon.go
> +func AccrualCheckDaemon(ctx context.Context, logger *zap.SugaredLogger, storage UnfinishedOrdersStorageInt, accrualSystemAddress string) {
```suggestion
func AccrualCheckDaemon(ctx context.Context, logger *zap.SugaredLogger, storage UnfinishedOrdersStorageInt, accrualSystemAddress string, wg &sync.WaitGroup) {
    defer wg.Done()
```

При шатдауне желательно дождаться завершения работы accrual-интерфейса, чтобы не потерять данные или не попасть на панику.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/accrualdaemon/accrual_daemon.go
> +				time.Sleep(time.Duration(seconds))
```suggestion
				time.Sleep(time.Duration(seconds) * time.Second)
```
Duration измеряется в наносекундах.

2024-08-22 22:36 UTC, avhitrov commented on cmd/gophermart/main.go
> +
Здесь бы завести слушалку для сигналов от системы и формировать на базе ее мягкий шатдаун.

2024-08-22 22:36 UTC, avhitrov commented on internal/app/handlers/required_interfaces.go
> +	SaveUser(login string, passwordHash string, passwordSalt string, ctx context.Context) (int, error) //int - ID
```suggestion
	SaveUser(ctx context.Context, login string, passwordHash string, passwordSalt string) (int, error) //int - ID
```
Go-style - всегда передавать контекст первым параметром. Касается всех функций из интерфейса.

2024-08-22 22:36 UTC, avhitrov commented on pkg/databases/postgresql.go
> +}
Имеет смысл логику этой функции включить в UpdateOrder (для status=PROCESSED) и объединить одной транзакцией. Или сделать общую функцию для сохранения успешного начисления. Потому как если в результате последовательного вызова UpdateOrder и AddToBalance во второй функции произойдет сбой - возникнет неконсистентность.

2024-08-22 22:36 UTC, avhitrov commented on pkg/databases/postgresql.go
> +		WHERE user_id = $1`, userID).Scan(&currentBalance)
```suggestion
		WHERE user_id = $1 FOR UPDATE`, userID).Scan(&currentBalance)
```
https://t.me/bushigo/36

2024-08-25 08:55 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +					continue
Не ту ошибку вписал на 69й, вместо второй должна быть ошибка ответа 500 от системы расчета баллов.

Fix

2024-08-25 08:57 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +			break loop
Fix

2024-08-25 09:15 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +
Fix

2024-08-25 09:23 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +func AccrualCheckDaemon(ctx context.Context, logger *zap.SugaredLogger, storage UnfinishedOrdersStorageInt, accrualSystemAddress string) {
fix

2024-08-25 09:25 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +				time.Sleep(time.Duration(seconds))
fix

2024-08-25 09:29 UTC, Lesnoi3283 commented on pkg/databases/postgresql.go
> +		WHERE user_id = $1`, userID).Scan(&currentBalance)
fix

2024-08-25 18:04 UTC, Lesnoi3283 commented on cmd/gophermart/main.go
> +
Добавил

2024-08-25 19:03 UTC, Lesnoi3283 commented on internal/app/accrualdaemon/accrual_daemon.go
> +
Поставил 7 секунд, так как на 30 секундном ожидании валились тесты (не дожидались обновления заказа)

2024-08-26 13:27 UTC, Lesnoi3283 commented on pkg/databases/postgresql.go
> +}
Сделал

2024-08-26 14:50 UTC, Lesnoi3283 commented on internal/app/handlers/required_interfaces.go
> +	SaveUser(login string, passwordHash string, passwordSalt string, ctx context.Context) (int, error) //int - ID
Готово

2024-08-27 22:35 UTC, avhitrov approved these changes
Все комментарии учтены. Отлично!

2024-08-28 04:31 UTC, merged